### ISSUE TITLE
 cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' 

### ISSUE THREAD

**Issue by EddieEduardo** [FinalFlowers/pedestrian_tracking#1]
Hi， thanks for sharing your code.

These days  I tried to run it, but I met with some errors as follows:

**Traceback (most recent call last):
  File "htc_deepsort.py", line 13, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\apis\inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\core\__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\core\post_processing\__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\core\post_processing\bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\ops\__init__.py", line 2, in <module>
    from .conv import build_conv_layer
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\ops\conv.py", line 4, in <module>
    from .dcn import DeformConvPack, ModulatedDeformConvPack
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\ops\dcn\deform_conv.py", line 11, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (J:\MOTS\MOT CODES\pedestrian_tracking-master\mmdet\ops\dcn\__init__.py)**

Could you please tell me how to fix it ? Thanks very much.

**Comment by FinalFlowers** [comment]
It seems that mmdetection was not correctly compiled.
To use deformable convolution, you need to compile the project on Linux by
`pip install -v -e .  # or "python setup.py develop"`
You can get more information about the compilation process through [install.md of mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md)

Also, CUDA should be configured correctly. You can check to see if CUDA is configured correctly in the following code
`import torch`
`print torch.cuda.is_available()`
